export function Fonts() {
  return (
    <>
      <link
        rel="preload"
        href="https://storage.googleapis.com/underdog-protocol/fonts/Aeonik/Aeonik-Bold.woff"
        as="font"
        crossOrigin="anonymous"
      />
      <link
        rel="preload"
        href="https://storage.googleapis.com/underdog-protocol/fonts/Aeonik/Aeonik-BoldItalic.woff"
        as="font"
        crossOrigin="anonymous"
      />
      <link
        rel="preload"
        href="https://storage.googleapis.com/underdog-protocol/fonts/Aeonik/Aeonik-Light.woff"
        as="font"
        crossOrigin="anonymous"
      />
      <link
        rel="preload"
        href="https://storage.googleapis.com/underdog-protocol/fonts/Aeonik/Aeonik-LightItalic.woff"
        as="font"
        crossOrigin="anonymous"
      />
      <link
        rel="preload"
        href="https://storage.googleapis.com/underdog-protocol/fonts/Aeonik/Aeonik-Regular.woff"
        as="font"
        crossOrigin="anonymous"
      />
      <link
        rel="preload"
        href="https://storage.googleapis.com/underdog-protocol/fonts/Aeonik/Aeonik-RegularItalic.woff"
        as="font"
        crossOrigin="anonymous"
      />
      <link
        rel="preload"
        href="https://storage.googleapis.com/underdog-protocol/fonts/Aeonik/Aeonik-Bold.woff2"
        as="font"
        crossOrigin="anonymous"
      />
      <link
        rel="preload"
        href="https://storage.googleapis.com/underdog-protocol/fonts/Aeonik/Aeonik-BoldItalic.woff2"
        as="font"
        crossOrigin="anonymous"
      />
      <link
        rel="preload"
        href="https://storage.googleapis.com/underdog-protocol/fonts/Aeonik/Aeonik-Light.woff2"
        as="font"
        crossOrigin="anonymous"
      />
      <link
        rel="preload"
        href="https://storage.googleapis.com/underdog-protocol/fonts/Aeonik/Aeonik-LightItalic.woff2"
        as="font"
        crossOrigin="anonymous"
      />
      <link
        rel="preload"
        href="https://storage.googleapis.com/underdog-protocol/fonts/Aeonik/Aeonik-Regular.woff2"
        as="font"
        crossOrigin="anonymous"
      />
      <link
        rel="preload"
        href="https://storage.googleapis.com/underdog-protocol/fonts/Aeonik/Aeonik-RegularItalic.woff2"
        as="font"
        crossOrigin="anonymous"
      />
      <link
        rel="preload"
        href="https://storage.googleapis.com/underdog-protocol/fonts/GT%20Super/GT-Super-Display-Light-Italic.woff2"
        as="font"
        crossOrigin="anonymous"
      />
      <link
        rel="preload"
        href="https://storage.googleapis.com/underdog-protocol/fonts/GT%20Super/GT-Super-Text-Medium.woff2"
        as="font"
        crossOrigin="anonymous"
      />
      <link
        rel="preload"
        href="https://storage.googleapis.com/underdog-protocol/fonts/GT%20Super/GT-Super-Text-Regular.woff2"
        as="font"
        crossOrigin="anonymous"
      />
    </>
  );
}
